global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/c7949e6c-59a5-418f-a8bc-e2412b6b3afe'
          send_resolved: false
